### ISSUE TITLE
Frontend lecturer view dashboard

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/gits-frontend#223] opened 2023-09-24 09:16 UTC
## Description
Currently the old version of the student view is shown to lecturers in the dashboard.

![Image](https://github.com/IT-REX-Platform/gits-frontend/assets/49751191/62198d1a-9977-48a7-a70d-b53a5a5a30d4)

The lecturer does not need a course progress bar and suggestions.
The title could be made clickable and the button "show details" could be changed to edit course.

## Acceptance Criteria
- [ ] dashboard has been changed

**Comment by SkyDiverStar** [comment] 2023-09-26 07:48
Duplicate of #219

**Closed by SkyDiverStar** 2023-09-26 07:48 UTC
Labels: frontend
